import Head from "next/head";
import Navbar from "../../components/Navbar";
import ProjectPreview from "../../components/ProjectPreview";
import Dribbble from "../../public/dribbble.svg";
import Instagram from "../../public/instagram.svg";
import Twitter from "../../public/twitter.svg";
import Linkedin from "../../public/linkedin.svg";
import SocialButton from "../../components/SocialButton";
import ReactDOM from 'react-dom';
import Tilt from 'react-parallax-tilt';



export default function Home() {
  return (
    <>
    
      <Head>
        <title>My portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <section className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4 mb-4 " >
        <div className="bg-zinc-400 h-[30rem] rounded-3xl min-h-max p-10 flex flex-col gap-7 bg-cover kolom ">
          <h1 className="text-4xl font-semibold lg:text-5xl">
            Hello, I&lsquo;m  Diaz, Web Development and Designer Web.
          </h1>
          <p className="flex-1">
            I care a lot about using design for positive impact and enjoy
            creating user-centric, delightful, and human experiences.
          </p>
          <div className="flex flex-col lg:flex-row items-center gap-4 justify-self-end">
            <a href="mailto:diazdgirgani93@gmai.com">
            <button className="bg-black text-white font-medium py-3 px-12 rounded-full w-60 lg:w-auto hover:bg-slate-600 transition duration-500">
              Contact me
            </button>
            </a>
            
            <div className="flex items-center gap-4" >
              <a href="https://github.com/MuhammadDiazGirgani" target="_blank">
                <SocialButton bgColor="github">
                <Dribbble className="w-5 h-5" />
              </SocialButton>
              </a>
              <a href="https://www.instagram.com/diazzgirgani/" target="_blank">
              <SocialButton bgColor="instagram">
                <Instagram className="w-5 h-5" />
              </SocialButton>
              </a>
              <a href="#">
              <SocialButton bgColor="twitter">
                <Twitter className="w-5 h-5" />
              </SocialButton>
              </a>
              <a href="#">
              <SocialButton bgColor="linkedin">
                <Linkedin className="w-5 h-5" />
              </SocialButton>
              </a>
            </div>
          </div>
        </div>
        <div className="h-[17rem] w-[11.5rem] rounded-3xl lg:h-[30rem] lg:w-[23rem] p-8  bg-[url('/profile.jpg')] hover:bg-[url('/profile2.jpg')] duration-500 bg-cover bg-center " />
        
      </section>

      
      <section className="project grid grid-cols-1 lg:grid-cols-2 gap-4 my-4 " id="projects">
 
      <Tilt>
        <ProjectPreview
        
          name="Zakatkeun App"
          description="web application for zakat built with html, css, javascript, php, mysql, bootstrap."
          imageUrl="/project-1.png"
          bgColor="#242f49"
          dark
        />
    </Tilt>
  
    <Tilt>
        <a href="https://datamining-regresi-linear-dg.000webhostapp.com/" target="_blank">
        <ProjectPreview
        
          name="Datamining App"
          description="web application for linear regression calculations built using html, css, javascript, php, mysql, bootstrap."
          imageUrl="/project-2.png"
          bgColor="#0E1744"
          dark
        />
        </a>
        </Tilt>
        <Tilt>
        <ProjectPreview
          name="Portfolio "
          description="This is my first portfolio using html and css only "
          imageUrl="/project-3.png"
          bgColor="#001B26"
          dark
        />
     </Tilt>
     <div className="skill">
     <Tilt>
        <ProjectPreview
          name="Skills "
          description="This is my skill, but some languages ​​are still being learned"
          imageUrl="/project-4.png"
          bgColor="#b3c2d8"
          
        />
        
</Tilt>
</div>
<div className="h-[17rem] w-[11.5rem] rounded-3xl lg:h-[30rem] lg:w-[23rem] p-8  bg-[url('/profile3.jpg')] hover:bg-[url('/profile4.jpg')] duration-500 bg-cover bg-center profil2" />
      </section>
      <section className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4 mb-4" id="contact" >

        <div className="h-[30rem] lg:w-[43.5rem] rounded-3xl min-h-max p-10 flex flex-col gap-7 kolom">
          
          <h1 className="text-4xl font-semibold lg:text-5xl">
          Want to work together?
          </h1>
          <p className="flex-1">
          Feel free to reach out for collaborations or just a friendly hello
          <p className="mt-6">
diazdgirgani93@gmail.com</p>
          </p>
         
          <div className="flex flex-col lg:flex-row items-center gap-4 justify-self-end  ">
          <a href="mailto:diazdgirgani93@gmai.com">
            <button className="bg-black text-white font-medium  py-3 px-12 rounded-full w-60 lg:w-auto hover:bg-slate-600 transition duration-500">
              Contact me
            </button>
            </a>
            <div className="flex items-center gap-4 " >
              <a href="https://github.com/MuhammadDiazGirgani" target="_blank">
                <SocialButton bgColor="github">
                <Dribbble className="w-5 h-5" />
              </SocialButton>
              </a>
              <a href="https://www.instagram.com/diazzgirgani/" target="_blank">
              <SocialButton bgColor="instagram">
                <Instagram className="w-5 h-5" />
              </SocialButton>
              </a>
           
              <SocialButton bgColor="twitter">
                <Twitter className="w-5 h-5" />
              </SocialButton>
             
             
              <SocialButton bgColor="linkedin">
                <Linkedin className="w-5 h-5" />
              </SocialButton>
            
            </div>
          </div>
        </div>
       
      </section>
    </>
    
  );
}
